image: node:16.13.2-alpine

stages:
  - test
  - analyze
  # - release

test:
  stage: test
  script:
    - npm i -g lerna yarn
    - lerna bootstrap
    - yarn coverage

analyze:sonar:
  stage: analyze
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: 0
  image:
    name: sonarsource/sonar-scanner-cli:4.7
    entrypoint: ['']
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    # - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=src -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD -Dsonar.exclusions=**/express/routers/**,**/rabbit-rpc/routers/**,**/mocks/**,**/*.stories.ts,**/*.stories.js -Dsonar.cpd.exclusions=**/router/**,**/utils/menu.ts -Dsonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts -Dsonar.javascript.coveragePlugin=lcov -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.testExecutionReportPaths=coverage/test-reporter.xml
  allow_failure: false
  only:
    - main
  tags:
    - nginx-proxy-sonar

.release:
  stage: release
  only:
    - main
  variables:
    GITLAB_AUTH_TOKEN: $CI_JOB_TOKEN
  tags:
    - gits-dev-mars
  when: manual

release:patch:
  extends: .release
  script:
    - npm run release -- --release-as patch
    - git push --follow-tags origin main && npm publish

release:minor:
  extends: .release
  script:
    - npm run release -- --release-as minor
    - git push --follow-tags origin main && npm publish
