stages:
    - analyze
    - release

analyze:sonar:
  stage: analyze
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: 0
  image:
    name: sonarsource/sonar-scanner-cli:4.5
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_USER -Dsonar.password=$SONAR_PASSWORD
  allow_failure: false
  only:
    - main
  tags:
    - nginx-proxy-sonar

.release:
  stage: release
  only:
    - main
  variables:
    GITLAB_AUTH_TOKEN: $CI_JOB_TOKEN
  tags:
    - gits-dev-mars
  when: manual

release:patch:
  extends: .release
  script:
    - npm run release -- --release-as patch
    
release:minor:
  extends: .release
  script:
    - npm run release -- --release-as minor
